on:
  push:
    branches:
      - main
      - master

name: Build

jobs:
  Build_deploy:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@master

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ubuntu-18.04-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: ubuntu-18.04-${{ steps.install-r.outputs.installed-r-version }}-1-

      - name: Install dependencies
        run: make install

      - name: build html
        run: make
        
      - name: build pdf
        run: make pdf

      - name: prepare deployment
        run: |
          mkdir docs
          mv index.html docs/
          if [ -d index_files ]; then
            mv index_files docs/
          fi
          mv assets docs/
          mv conf docs/
          mv images docs/
          mv slides.pdf docs/
      
      - name: Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          BRANCH: gh-pages
          FOLDER: docs
          SINGLE_COMMIT: true
